/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.4 at Tue Dec  3 15:43:00 2019. */

#include "lorasender.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t lorasender_request_fields[3] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, lorasender_request, command, command, 0),
    PB_FIELD(  2, BYTES   , OPTIONAL, CALLBACK, OTHER, lorasender_request, data, command, 0),
    PB_LAST_FIELD
};

const pb_field_t lorasender_reply_fields[4] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, lorasender_reply, msgid, msgid, 0),
    PB_FIELD(  2, UENUM   , REQUIRED, STATIC  , OTHER, lorasender_reply, type, msgid, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, CALLBACK, OTHER, lorasender_reply, details, type, 0),
    PB_LAST_FIELD
};




/* @@protoc_insertion_point(eof) */
